import { describe, expect, it } from "vitest";

import { filenameFromDisposition } from "../api";
import { crc32, renderDocx, zipStored } from "../mock/docx";
import { renderPdf, wrapText } from "../mock/pdf";
import { buildReportBlocks, PROTOCOL_COLUMNS, REPORT_FOOTER, reportFilename } from "../mock/report";
import { buildContractText, locateQuote, placeFindings, STUB_FINDINGS } from "../mock/seed";
import type { ContractDetail, Finding } from "../types";

const contract = (findings: Finding[], withEmail = true): ContractDetail => ({
  id: "c1",
  title: "Logo Design Agreement.pdf",
  filename: "Logo Design Agreement.pdf",
  file_type: "pdf",
  file_size: 1000,
  status: "done",
  created_at: "2026-09-01T10:00:00Z",
  updated_at: "2026-09-01T10:01:00Z",
  analyzed_at: "2026-09-01T10:01:00Z",
  overall_risk_level: "high",
  source_text: "text",
  risk_summary: { overall_risk_level: "high", high_count: 1, medium_count: 1, low_count: 1 },
  findings,
  email_draft: withEmail
    ? {
        id: "e1",
        subject: "Proposed changes",
        body: "Hello,\n\n- One",
        created_at: "2026-09-01T10:01:00Z",
      }
    : null,
});

const stubFindings = () => {
  const text = buildContractText("Sample.pdf", STUB_FINDINGS);
  return placeFindings(STUB_FINDINGS, text);
};

describe("finding offsets", () => {
  it("counts Unicode code points, not UTF-16 units", () => {
    expect(locateQuote("😀 Net 60 applies.", "Net 60")).toEqual({ start_char: 2, end_char: 8 });
  });

  it("returns null offsets when the quote is absent", () => {
    expect(locateQuote("Net 30 applies.", "Net 60")).toEqual({ start_char: null, end_char: null });
  });
});

describe("report content", () => {
  it("lists only high and medium findings in the protocol, high first", () => {
    const blocks = buildReportBlocks(contract(stubFindings()), "2026-09-02T08:30:00Z");
    const protocol = blocks.find((b) => b.kind === "table" && b.header === PROTOCOL_COLUMNS);
    expect(protocol).toBeDefined();
    if (protocol?.kind !== "table") return;
    expect(protocol.rows).toHaveLength(2);
    expect(protocol.rows[0]![1]).toMatch(/^Uncapped liability \(High\)\n/);
    expect(protocol.rows[1]![2]).toBe("Invoices are payable within 30 days of the invoice date.");
  });

  it("states the export time and leaves out the cover letter without an email", () => {
    const low = stubFindings().filter((f) => f.risk_level === "low");
    const blocks = buildReportBlocks(contract(low, false), "2026-09-02T08:30:00Z");
    const texts = blocks.map((b) => ("text" in b ? b.text : ""));
    expect(texts.join("\n")).toContain("Exported 2026-09-02 08:30 UTC");
    expect(texts).toContain("No clauses require negotiation.");
    expect(texts).not.toContain("Client Cover Letter");
  });

  it("sanitizes and truncates the filename", () => {
    expect(reportFilename("Q3: Acme/Beta SOW", "pdf")).toBe(
      "Q3_ Acme_Beta SOW - Counter-proposal.pdf",
    );
    expect(reportFilename("x".repeat(150), "docx")).toBe(
      `${"x".repeat(100)} - Counter-proposal.docx`,
    );
  });

  it("reads the filename from Content-Disposition", () => {
    expect(filenameFromDisposition('attachment; filename="a b.pdf"')).toBe("a b.pdf");
    expect(filenameFromDisposition(null)).toBeNull();
  });
});

describe("file writers", () => {
  it("wraps long words instead of cutting them", () => {
    const lines = wrapText("a".repeat(50), 100, 10);
    expect(lines.join("")).toBe("a".repeat(50));
  });

  it("writes a PDF whose xref offsets point at its objects", async () => {
    const blocks = buildReportBlocks(contract(stubFindings()), "2026-09-02T08:30:00Z");
    const pdf = new TextDecoder("latin1").decode(
      await renderPdf(blocks, REPORT_FOOTER).arrayBuffer(),
    );
    const xrefAt = Number(pdf.match(/startxref\n(\d+)/)![1]);
    expect(pdf.slice(xrefAt, xrefAt + 4)).toBe("xref");
    const offsets = [...pdf.matchAll(/^(\d{10}) 00000 n $/gm)].map((m) => Number(m[1]));
    offsets.forEach((offset, i) =>
      expect(pdf.slice(offset).startsWith(`${i + 1} 0 obj`)).toBe(true),
    );
    expect(pdf).toContain("Protocol of Disagreements");
  });

  it("computes the standard CRC-32", () => {
    expect(crc32(new TextEncoder().encode("123456789"))).toBe(0xcbf43926);
  });

  it("writes a DOCX package with the document, footer, and tables", async () => {
    const blocks = buildReportBlocks(contract(stubFindings()), "2026-09-02T08:30:00Z");
    const bytes = new Uint8Array(await renderDocx(blocks, REPORT_FOOTER).arrayBuffer());
    const text = new TextDecoder().decode(bytes);
    for (const part of ["[Content_Types].xml", "word/document.xml", "word/footer1.xml"]) {
      expect(text).toContain(part);
    }
    expect(text).toContain("<w:tbl>");
    expect(text).toContain("Generated by Anti-Scope Creep");
    expect(zipStored([]).length).toBe(22); // empty archive: end record only
  });
});
