from io import BytesIO
from uuid import uuid4

import pytest
from docx import Document
from pypdf import PdfReader

from tests.conftest import assert_error


def export(harness, headers, contract_id: str, fmt: str):
    return harness.client.post(f"/contracts/{contract_id}/export", json={"format": fmt}, headers=headers)


def pdf_text(content: bytes) -> str:
    return "\n".join(page.extract_text() for page in PdfReader(BytesIO(content)).pages)


def docx_text(content: bytes) -> str:
    document = Document(BytesIO(content))
    cells = [cell.text for table in document.tables for row in table.rows for cell in row.cells]
    footer = [p.text for p in document.sections[0].footer.paragraphs]
    return "\n".join([p.text for p in document.paragraphs] + cells + footer)


# The stub fixture: one high, one medium and one low finding, and an email draft.
EXPECTED = [
    "Pasted contract",
    "Executive Summary",
    "Overall risk: High.",
    "Protocol of Disagreements",
    "Client's Original Clause",
    "Uncapped liability (High)",
    "Long / unfavorable payment terms (Medium)",
    "shall not exceed the total fees paid under this Agreement",
    "Client Cover Letter",
    "Subject: Proposed changes to the agreement",
    "Generated by Anti-Scope Creep",
    "does not constitute professional legal advice",
]


@pytest.mark.parametrize(("fmt", "media_type", "read"), [
    ("pdf", "application/pdf", pdf_text),
    ("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", docx_text),
])
def test_export_returns_the_report_file(harness, auth_headers, fmt, media_type, read):
    contract_id = harness.create_contract(auth_headers)["id"]
    response = export(harness, auth_headers, contract_id, fmt)

    assert response.status_code == 200
    assert response.headers["content-type"] == media_type
    assert response.headers["content-disposition"] == f'attachment; filename="Pasted contract - Counter-proposal.{fmt}"'
    text = " ".join(read(response.content).split())
    for expected in EXPECTED:
        assert expected in text, expected
    assert "Unlimited revisions (Low)" not in text  # low findings are counted, not listed
    assert "Analyzed " in text and "Exported " in text and " UTC" in text


def test_export_without_results_is_409(harness, auth_headers):
    harness.use_recording_runner()  # the analysis never runs, so analyzed_at stays null
    contract_id = harness.create_contract(auth_headers)["id"]
    error = assert_error(export(harness, auth_headers, contract_id, "pdf"), 409, "NO_ANALYSIS_RESULTS")
    assert error["message"] == "This contract has no analysis results to export yet."


def test_the_filename_keeps_only_safe_title_characters(harness, auth_headers):
    contract_id = harness.paste(auth_headers, title="Smith & Co / “Design” — 2026?").json()["id"]
    response = export(harness, auth_headers, contract_id, "docx")
    assert response.headers["content-disposition"] == (
        'attachment; filename="Smith _ Co _ _Design_ _ 2026_ - Counter-proposal.docx"'
    )


@pytest.mark.parametrize("contract_id", [str(uuid4()), "not-a-uuid"])
def test_export_of_unknown_contract_is_404(client, auth_headers, contract_id):
    response = client.post(f"/contracts/{contract_id}/export", json={"format": "pdf"}, headers=auth_headers)
    assert_error(response, 404, "CONTRACT_NOT_FOUND")


@pytest.mark.parametrize(
    "payload", [{}, {"format": "txt"}, {"format": "PDF"}, {"format": "pdf", "logo": "x"}]
)
def test_export_validates_the_body(harness, auth_headers, payload):
    contract_id = harness.create_contract(auth_headers)["id"]
    response = harness.client.post(f"/contracts/{contract_id}/export", json=payload, headers=auth_headers)
    assert_error(response, 422, "VALIDATION_ERROR")


def test_export_requires_auth(harness, auth_headers):
    contract_id = harness.create_contract(auth_headers)["id"]
    response = harness.client.post(f"/contracts/{contract_id}/export", json={"format": "pdf"})
    assert_error(response, 401, "UNAUTHORIZED")


def test_the_filename_header_is_readable_cross_origin(harness, auth_headers):
    """The frontend runs on another origin and reads the filename from Content-Disposition."""
    contract_id = harness.create_contract(auth_headers)["id"]
    response = harness.client.post(
        f"/contracts/{contract_id}/export", json={"format": "pdf"},
        headers={**auth_headers, "Origin": "http://localhost:8080"},
    )
    assert response.headers["access-control-allow-origin"] == "http://localhost:8080"
    assert "content-disposition" in response.headers["access-control-expose-headers"].lower()
