// Content of the counter-proposal report (spec "POST /contracts/{id}/export"), independent of
// the file format. The mock renders it with ./pdf and ./docx.

import type { ContractDetail, ExportFormat, Finding, RiskLevel } from "../types";
import { LEGAL_DISCLAIMER, RISK_CATEGORY_LABELS } from "../types";

export type ReportBlock =
  | { kind: "title"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "table"; header: string[]; rows: string[][] };

export const REPORT_FOOTER = ["Generated by Anti-Scope Creep", LEGAL_DISCLAIMER];

export const PROTOCOL_COLUMNS = [
  "Client's Original Clause",
  "Identified Risk & Explanation",
  "Proposed Counter-Clause",
];

const LEVEL_LABELS: Record<RiskLevel, string> = { high: "High", medium: "Medium", low: "Low" };

/** `<title> - Counter-proposal.<ext>`; unsafe title characters become `_`, title cut to 100. */
export const reportFilename = (title: string, format: ExportFormat): string =>
  `${title.replace(/[^A-Za-z0-9 ._-]/g, "_").slice(0, 100)} - Counter-proposal.${format}`;

const formatUtc = (iso: string) => iso.replace("T", " ").replace(/:\d{2}Z$/, " UTC");

// Findings arrive sorted high -> medium -> low, so filtering keeps the required order.
const protocolRows = (findings: Finding[]): string[][] =>
  findings
    .filter((f) => f.risk_level !== "low")
    .map((f) => [
      f.quoted_text,
      `${RISK_CATEGORY_LABELS[f.category]} (${LEVEL_LABELS[f.risk_level]})\n${f.explanation}`,
      f.suggested_change,
    ]);

const summaryRows = (c: ContractDetail): string[][] => {
  const s = c.risk_summary!;
  const total = s.high_count + s.medium_count + s.low_count;
  return [
    ["High", String(s.high_count)],
    ["Medium", String(s.medium_count)],
    ["Low", String(s.low_count)],
    ["Total", String(total)],
  ];
};

/** The report blocks in order. Requires a contract with results (`analyzed_at` not null). */
export const buildReportBlocks = (c: ContractDetail, exportedAt: string): ReportBlock[] => {
  const overall = LEVEL_LABELS[c.risk_summary!.overall_risk_level];
  const rows = protocolRows(c.findings);
  const blocks: ReportBlock[] = [
    { kind: "title", text: c.title },
    {
      kind: "paragraph",
      text: `Analyzed ${formatUtc(c.analyzed_at!)}\nExported ${formatUtc(exportedAt)}\nOverall risk: ${overall}`,
    },
    { kind: "heading", text: "Executive Summary" },
    { kind: "table", header: ["Risk level", "Findings"], rows: summaryRows(c) },
    { kind: "paragraph", text: `Overall risk: ${overall}.` },
    { kind: "heading", text: "Protocol of Disagreements" },
    rows.length > 0
      ? { kind: "table", header: PROTOCOL_COLUMNS, rows }
      : { kind: "paragraph", text: "No clauses require negotiation." },
  ];
  if (c.email_draft) {
    blocks.push(
      { kind: "heading", text: "Client Cover Letter" },
      { kind: "paragraph", text: `Subject: ${c.email_draft.subject}` },
      { kind: "paragraph", text: c.email_draft.body },
    );
  }
  return blocks;
};
