"""Content of the counter-proposal report, independent of the file format.

docs/spec.md "POST /contracts/{id}/export" defines it: header, Executive Summary, Protocol of
Disagreements, Client Cover Letter, and a footer with the legal disclaimer. The frontend mock
builds the same blocks (frontend/src/services/mock/report.ts); report_pdf and report_docx
render them.
"""

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Literal

from app.models import ContractDetail, Finding, RiskCategory, RiskLevel

ExportFormat = Literal["pdf", "docx"]

LEGAL_DISCLAIMER = (
    "Anti-Scope Creep uses automated AI analysis to identify potential commercial contract risks "
    "and does not constitute professional legal advice."
)
REPORT_FOOTER = ("Generated by Anti-Scope Creep", LEGAL_DISCLAIMER)
PROTOCOL_COLUMNS = ("Client's Original Clause", "Identified Risk & Explanation", "Proposed Counter-Clause")
NO_NEGOTIATION = "No clauses require negotiation."

RISK_CATEGORY_LABELS = {
    RiskCategory.SCOPE_CREEP: "Scope ambiguity / scope creep",
    RiskCategory.UNLIMITED_REVISIONS: "Unlimited revisions",
    RiskCategory.ONE_SIDED_TERMINATION: "One-sided termination",
    RiskCategory.IP_TRANSFER_BEFORE_PAYMENT: "IP transfer before payment",
    RiskCategory.UNCAPPED_LIABILITY: "Uncapped liability",
    RiskCategory.UNFAVORABLE_PAYMENT_TERMS: "Long / unfavorable payment terms",
}
LEVEL_LABELS = {RiskLevel.HIGH: "High", RiskLevel.MEDIUM: "Medium", RiskLevel.LOW: "Low"}
MEDIA_TYPES = {
    "pdf": "application/pdf",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
}


@dataclass(frozen=True)
class Block:
    kind: Literal["title", "heading", "paragraph", "table"]
    text: str = ""
    header: tuple[str, ...] = ()
    rows: tuple[tuple[str, ...], ...] = ()


def report_filename(title: str, export_format: ExportFormat) -> str:
    """`<title> - Counter-proposal.<ext>`; unsafe title characters become `_`, title cut to 100."""
    return f"{re.sub(r'[^A-Za-z0-9 ._-]', '_', title)[:100]} - Counter-proposal.{export_format}"


def report_blocks(contract: ContractDetail, exported_at: datetime) -> list[Block]:
    """The report in order. Requires results: `analyzed_at` and `risk_summary` are set."""
    if contract.analyzed_at is None or contract.risk_summary is None:
        raise ValueError("The contract has no analysis results")
    overall = LEVEL_LABELS[contract.risk_summary.overall_risk_level]
    rows = _protocol_rows(contract.findings)
    blocks = [
        Block("title", contract.title),
        Block(
            "paragraph",
            f"Analyzed {_utc(contract.analyzed_at)}\nExported {_utc(exported_at)}\nOverall risk: {overall}",
        ),
        Block("heading", "Executive Summary"),
        Block("table", header=("Risk level", "Findings"), rows=_summary_rows(contract)),
        Block("paragraph", f"Overall risk: {overall}."),
        Block("heading", "Protocol of Disagreements"),
        Block("table", header=PROTOCOL_COLUMNS, rows=rows) if rows else Block("paragraph", NO_NEGOTIATION),
    ]
    if contract.email_draft is not None:
        blocks += [
            Block("heading", "Client Cover Letter"),
            Block("paragraph", f"Subject: {contract.email_draft.subject}"),
            Block("paragraph", contract.email_draft.body),
        ]
    return blocks


def _protocol_rows(findings: list[Finding]) -> tuple[tuple[str, ...], ...]:
    # Findings arrive sorted high -> medium -> low, so filtering keeps the required order.
    return tuple(
        (
            f.quoted_text,
            f"{RISK_CATEGORY_LABELS[f.category]} ({LEVEL_LABELS[f.risk_level]})\n{f.explanation}",
            f.suggested_change,
        )
        for f in findings
        if f.risk_level != RiskLevel.LOW
    )


def _summary_rows(contract: ContractDetail) -> tuple[tuple[str, ...], ...]:
    summary = contract.risk_summary
    assert summary is not None
    counts = (summary.high_count, summary.medium_count, summary.low_count)
    return (
        ("High", str(counts[0])),
        ("Medium", str(counts[1])),
        ("Low", str(counts[2])),
        ("Total", str(sum(counts))),
    )


def _utc(moment: datetime) -> str:
    if moment.tzinfo is not None:
        moment = moment.astimezone(timezone.utc)
    return moment.strftime("%Y-%m-%d %H:%M UTC")
